global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "marketplace-monitor"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service-1:3001"]
    metrics_path: "/metrics"

  - job_name: "catalog-service"
    static_configs:
      - targets: ["catalog-service-1:3002"]
    metrics_path: "/metrics"

  - job_name: "order-service"
    static_configs:
      - targets: ["order-service-1:3003"]
    metrics_path: "/metrics"

  - job_name: "analytics-service"
    static_configs:
      - targets: ["analytics-service:3004"]
    metrics_path: "/metrics"
